<a href="https://colab.research.google.com/github/Paengpeng/229352-StatisticalLearning/blob/main/229352_Lab08.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Statistical Learning for Data Science 2 (229352)
#### Instructor: Donlapark Ponnoprat

#### [Course website](https://donlapark.pages.dev/229352/)

## Lab #8

There are several deep learning frameworks in Python.

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/PyTorch_logo_black.svg/2560px-PyTorch_logo_black.svg.png" width="100"/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src="https://upload.wikimedia.org/wikipedia/commons/2/2d/Tensorflow_logo.svg" width="40"/><img src="https://assets-global.website-files.com/621e749a546b7592125f38ed/62277da165ed192adba475fc_JAX.jpg" width="100"/>

In this Lab, we will use PyTorch

In [1]:
import numpy as np

import torch

# Tensor basics

## Basic tensor creation

### Creating a scalar (1D) tensor

In [2]:
scalar = torch.tensor(7)
print(f"Scalar tensor: {scalar}")
print(f"Type: {type(scalar)}")
print(f"Shape: {scalar.shape}")
print(f"Dimension: {scalar.ndim}")

Scalar tensor: 7
Type: <class 'torch.Tensor'>
Shape: torch.Size([])
Dimension: 0


### Convert a tensor to scalar

In [3]:
scalar_tensor = torch.tensor(42)
print(f"Scalar tensor: {scalar_tensor}")
print(f"Type: {type(scalar_tensor)}")

scalar_value = scalar_tensor.item()
print(f"\nConverted to Python scalar using .item(): {scalar_value}")
print(f"Type: {type(scalar_value)}")

scalar_int = int(scalar_tensor)
print(f"\nConverted using int(): {scalar_int}")
print(f"Type: {type(scalar_int)}")

float_tensor = torch.tensor(3.14159)
scalar_float = float_tensor.item()
print(f"\nFloat tensor: {float_tensor}")
print(f"Converted to Python float: {scalar_float}")
print(f"Type: {type(scalar_float)}")

print("\nNote: .item() only works with tensors containing a single value")

Scalar tensor: 42
Type: <class 'torch.Tensor'>

Converted to Python scalar using .item(): 42
Type: <class 'int'>

Converted using int(): 42
Type: <class 'int'>

Float tensor: 3.141590118408203
Converted to Python float: 3.141590118408203
Type: <class 'float'>

Note: .item() only works with tensors containing a single value


### Creating 2D tensor

In [9]:
tensor_2d = torch.tensor([[1, 2, 3],
                          [4, 5, 6],
                          [7, 8, 9]])
print(f"2D tensor:\n{tensor_2d}")
print(f"Shape: {tensor_2d.shape}")
print(f"Dimension: {tensor_2d.ndim}")


2D tensor:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Shape: torch.Size([3, 3])
Dimension: 2


## Tensor and Numpy

### Convert from tensor to numpy array

In [5]:
tensor_example = torch.tensor([[1, 2, 3],
                               [4, 5, 6]])
numpy_array = tensor_example.numpy()

print(f"Original tensor:\n{tensor_example}")
print(f"\nConverted to numpy array:\n{numpy_array}")
print(f"Type of numpy array: {type(numpy_array)}")

Original tensor:
tensor([[1, 2, 3],
        [4, 5, 6]])

Converted to numpy array:
[[1 2 3]
 [4 5 6]]
Type of numpy array: <class 'numpy.ndarray'>


### Convert from numpy array to tensor

In [6]:
numpy_array_example = np.array([[10, 20, 30],
                                [40, 50, 60]])
tensor_from_numpy = torch.from_numpy(numpy_array_example)

print(f"Original numpy array:\n{numpy_array_example}")
print(f"\nConverted to tensor:\n{tensor_from_numpy}")
print(f"Type of tensor: {type(tensor_from_numpy)}")

Original numpy array:
[[10 20 30]
 [40 50 60]]

Converted to tensor:
tensor([[10, 20, 30],
        [40, 50, 60]])
Type of tensor: <class 'torch.Tensor'>


## PyTorch and GPU

check if GPU is available

In [7]:
torch.cuda.is_available()

True

In [12]:
if gpu_available := torch.cuda.is_available():
    print("GPU is available")
    print(f"GPU device name: {torch.cuda.get_device_name(0)}")
    print(f"Number of GPUs: {torch.cuda.device_count()}")
else:
    print("No GPU available, using CPU")

GPU is available
GPU device name: Tesla T4
Number of GPUs: 1


In [13]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"\nUsing device: {device}")


Using device: cuda


In [14]:
tensor_cpu = torch.tensor([1, 2, 3, 4, 5])
tensor_device = tensor_cpu.to(device)
print(f"Tensor on device: {tensor_device.device}")

Tensor on device: cuda:0


## Basic operations

In [15]:
a = torch.tensor([1, 2, 3, 4])
b = torch.tensor([5, 6, 7, 8])

print(f"a = {a}")
print(f"b = {b}")
print(f"\na + b = {a + b}")
print(f"a - b = {a - b}")
print(f"a * b = {a * b}")
print(f"a / b = {a / b}")
print(f"a ** 2 = {a ** 2}")

a = tensor([1, 2, 3, 4])
b = tensor([5, 6, 7, 8])

a + b = tensor([ 6,  8, 10, 12])
a - b = tensor([-4, -4, -4, -4])
a * b = tensor([ 5, 12, 21, 32])
a / b = tensor([0.2000, 0.3333, 0.4286, 0.5000])
a ** 2 = tensor([ 1,  4,  9, 16])


### Matrix multiplication

In [17]:
matrix_a = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
matrix_b = torch.tensor([[7, 8, 9],
                         [10, 11, 12]])

print(f"Matrix A (3x2):\n{matrix_a}")
print(f"\nMatrix B (2x3):\n{matrix_b}")

result_matmul = matrix_a @ matrix_b
print(f"\nA @ B (using @):\n{result_matmul}")

result_matmul2 = torch.matmul(matrix_a, matrix_b)
print(f"\nA @ B (using torch.matmul):\n{result_matmul2}")

result_mm = torch.mm(matrix_a, matrix_b)
print(f"\nA @ B (using torch.mm):\n{result_mm}")

Matrix A (3x2):
tensor([[1, 2],
        [3, 4],
        [5, 6]])

Matrix B (2x3):
tensor([[ 7,  8,  9],
        [10, 11, 12]])

A @ B (using @):
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

A @ B (using torch.matmul):
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

A @ B (using torch.mm):
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


### Matrix transpose

In [18]:
matrix = torch.tensor([[1, 2, 3],
                       [4, 5, 6]])
print(f"Original matrix:\n{matrix}")
print(f"Shape: {matrix.shape}")

transposed = matrix.T
print(f"\nTransposed matrix:\n{transposed}")
print(f"Shape: {transposed.shape}")

transposed2 = matrix.transpose(0, 1)
print(f"\nTransposed (using transpose):\n{transposed2}")

Original matrix:
tensor([[1, 2, 3],
        [4, 5, 6]])
Shape: torch.Size([2, 3])

Transposed matrix:
tensor([[1, 4],
        [2, 5],
        [3, 6]])
Shape: torch.Size([3, 2])

Transposed (using transpose):
tensor([[1, 4],
        [2, 5],
        [3, 6]])


## Creating a specific type of tensor

In [19]:
zeros = torch.zeros(3, 4)
print(f"Zeros tensor (3x4):\n{zeros}")

ones = torch.ones(2, 3)
print(f"\nOnes tensor (2x3):\n{ones}")

random = torch.rand(2, 3)
print(f"\nRandom tensor (2x3):\n{random}")

randn = torch.randn(2, 3)
print(f"\nRandom normal tensor (2x3):\n{randn}")

range_tensor = torch.arange(0, 10, 2)
print(f"\nRange tensor (0 to 10, step 2): {range_tensor}")

linspace_tensor = torch.linspace(0, 1, 5)
print(f"\nLinspace tensor (0 to 1, 5 steps): {linspace_tensor}")

identity = torch.eye(3)
print(f"\nIdentity matrix (3x3):\n{identity}")

float_tensor = torch.tensor([1, 2, 3], dtype=torch.float32)
print(f"\nFloat32 tensor: {float_tensor}, dtype: {float_tensor.dtype}")

int_tensor = torch.tensor([1.5, 2.7, 3.9], dtype=torch.int32)
print(f"Int32 tensor: {int_tensor}, dtype: {int_tensor.dtype}")

Zeros tensor (3x4):
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

Ones tensor (2x3):
tensor([[1., 1., 1.],
        [1., 1., 1.]])

Random tensor (2x3):
tensor([[0.3276, 0.4179, 0.5164],
        [0.8704, 0.6448, 0.0638]])

Random normal tensor (2x3):
tensor([[-1.6196,  0.4807, -1.8285],
        [ 0.2304, -0.6213, -0.7267]])

Range tensor (0 to 10, step 2): tensor([0, 2, 4, 6, 8])

Linspace tensor (0 to 1, 5 steps): tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])

Identity matrix (3x3):
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

Float32 tensor: tensor([1., 2., 3.]), dtype: torch.float32
Int32 tensor: tensor([1, 2, 3], dtype=torch.int32), dtype: torch.int32


## Tensor's shape

### Checking the shape of a tensor

In [20]:
tensor = torch.tensor([[1, 2, 3, 4],
                       [5, 6, 7, 8],
                       [9, 10, 11, 12]])
print(f"Tensor:\n{tensor}")
print(f"\nShape: {tensor.shape}")
print(f"Size: {tensor.size()}")
print(f"Number of dimensions: {tensor.ndim}")
print(f"Total elements: {tensor.numel()}")

Tensor:
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

Shape: torch.Size([3, 4])
Size: torch.Size([3, 4])
Number of dimensions: 2
Total elements: 12


### Changing the shape of a tensor

In [21]:
original = torch.arange(12)
print(f"Original tensor (12,): {original}")

reshaped = original.reshape(3, 4)
print(f"\nReshaped to (3, 4):\n{reshaped}")

reshaped2 = original.reshape(2, 6)
print(f"\nReshaped to (2, 6):\n{reshaped2}")

reshaped3 = original.reshape(4, -1)
print(f"\nReshaped to (4, -1) = (4, 3):\n{reshaped3}")

print("\n--- Using view (memory efficient) ---")
viewed = original.view(3, 4)
print(f"Viewed as (3, 4):\n{viewed}")

print("\nNote: reshape creates a copy if needed, view requires contiguous memory")

Original tensor (12,): tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

Reshaped to (3, 4):
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

Reshaped to (2, 6):
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])

Reshaped to (4, -1) = (4, 3):
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

--- Using view (memory efficient) ---
Viewed as (3, 4):
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

Note: reshape creates a copy if needed, view requires contiguous memory


In general, use `reshape`, but if you are worried about the memory usage, use `view`.

### Stacking and concatenating tensors

In [22]:
tensor1 = torch.tensor([[1, 2],
                        [3, 4]])
tensor2 = torch.tensor([[5, 6],
                        [7, 8]])

print(f"Tensor 1:\n{tensor1}")
print(f"\nTensor 2:\n{tensor2}")

# Concatenate
concat_dim0 = torch.cat([tensor1, tensor2], dim=0)
print(f"\nConcatenate along dim=0 (vertical):\n{concat_dim0}")
print(f"Shape: {concat_dim0.shape}")

concat_dim1 = torch.cat([tensor1, tensor2], dim=1)
print(f"\nConcatenate along dim=1 (horizontal):\n{concat_dim1}")
print(f"Shape: {concat_dim1.shape}")

# Stack
stacked_dim0 = torch.stack([tensor1, tensor2], dim=0)
print(f"\nStack along dim=0:\n{stacked_dim0}")
print(f"Shape: {stacked_dim0.shape}")

stacked_dim1 = torch.stack([tensor1, tensor2], dim=1)
print(f"\nStack along dim=1:\n{stacked_dim1}")
print(f"Shape: {stacked_dim1.shape}")

Tensor 1:
tensor([[1, 2],
        [3, 4]])

Tensor 2:
tensor([[5, 6],
        [7, 8]])

Concatenate along dim=0 (vertical):
tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
Shape: torch.Size([4, 2])

Concatenate along dim=1 (horizontal):
tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])
Shape: torch.Size([2, 4])

Stack along dim=0:
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
Shape: torch.Size([2, 2, 2])

Stack along dim=1:
tensor([[[1, 2],
         [5, 6]],

        [[3, 4],
         [7, 8]]])
Shape: torch.Size([2, 2, 2])


### Squeezing a tensor (removing an extra dimension)

In [23]:
tensor_with_extra_dim = torch.tensor([[[1, 2, 3]]])
print(f"Tensor with extra dimensions: {tensor_with_extra_dim}")
print(f"Shape: {tensor_with_extra_dim.shape}")

squeezed = tensor_with_extra_dim.squeeze()
print(f"\nSqueezed tensor: {squeezed}")
print(f"Shape: {squeezed.shape}")

Tensor with extra dimensions: tensor([[[1, 2, 3]]])
Shape: torch.Size([1, 1, 3])

Squeezed tensor: tensor([1, 2, 3])
Shape: torch.Size([3])


In [24]:
tensor_2 = torch.zeros(2, 1, 3, 1, 4)
print(f"\nTensor shape: {tensor_2.shape}")
squeezed_dim1 = tensor_2.squeeze(1)
print(f"Squeezed dim 1: {squeezed_dim1.shape}")


Tensor shape: torch.Size([2, 1, 3, 1, 4])
Squeezed dim 1: torch.Size([2, 3, 1, 4])


### Unsqueezing a tensor (adding an extra dimension)

In [25]:
# H.shape = (6, )
H = torch.tensor([1, 2, 3, 4, 5, 6])
print(f"Original tensor H: {H}")
print(f"H.shape = {H.shape}")

unsqueezed_0 = H.unsqueeze(0)
print(f"\nUnsqueezed at dim=0: {unsqueezed_0}")
print(f"Shape: {unsqueezed_0.shape}")

unsqueezed_1 = H.unsqueeze(1)
print(f"\nUnsqueezed at dim=1:\n{unsqueezed_1}")
print(f"Shape: {unsqueezed_1.shape}")

unsqueezed_minus1 = H.unsqueeze(-1)
print(f"\nUnsqueezed at dim=-1:\n{unsqueezed_minus1}")
print(f"Shape: {unsqueezed_minus1.shape}")

unsqueezed_alt = H[None, :]
print(f"\nUsing indexing H[None, :]: {unsqueezed_alt}")
print(f"Shape: {unsqueezed_alt.shape}")

Original tensor H: tensor([1, 2, 3, 4, 5, 6])
H.shape = torch.Size([6])

Unsqueezed at dim=0: tensor([[1, 2, 3, 4, 5, 6]])
Shape: torch.Size([1, 6])

Unsqueezed at dim=1:
tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])
Shape: torch.Size([6, 1])

Unsqueezed at dim=-1:
tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])
Shape: torch.Size([6, 1])

Using indexing H[None, :]: tensor([[1, 2, 3, 4, 5, 6]])
Shape: torch.Size([1, 6])


## Indexing

In [26]:
P = torch.arange(12).reshape(3,4)
print(P)
print(P[0])
print(P[:, 0])
print(P[-1])
print(P[:, -1])
print(P[-2:])
print(P[:, -2:])

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([0, 1, 2, 3])
tensor([0, 4, 8])
tensor([ 8,  9, 10, 11])
tensor([ 3,  7, 11])
tensor([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 2,  3],
        [ 6,  7],
        [10, 11]])


# Exercise

In this exercise, we will simulate data to perform linear regression with 200 rows and 7 variables.

1. Create three random $N(0,1)$ tensors: `X`, `b` and `e` with `X.shape = (200, 7)`, `b.shape = (8, 1)` and `e.shape = (200, 1)` respectively.
2. Create a tensor that contains only 1's with shape `(200, 1)`.
3. Modify tensor `X` by adding the tensor in 2. as the first column.
4. Compute `y` using the following formula:
$$ y = Xb + e $$.
5. Fit a linear regression to the data `X` and `y` and obtain a tensor of estimated coefficient `b_hat`. The formula for `b_hat` is given by:
$$ \hat{b} = (X^TX)^{-1}X^Ty $$
Note: use `torch.inverse(...)` to calculate the inverse
6. Compute the predictions `y_hat`, given by:
$$ \hat{y} = X\hat{b} $$
7. Convert both `y` and `y_hat` from tensor to Numpy array and calculate MSE:
$$ MSE = \frac{1}{200}\sum_{i=1}^{200} (y_i - \hat{y}_i)^2 $$

In [27]:
X = torch.tensor([[2, 3, 2], [4, 6, 7], [7, 2, 4]])
print(X)

X = torch.tensor([[1, 2, 3, 2], [1, 4, 6, 7], [1, 7, 2, 4]])
print(X)

tensor([[2, 3, 2],
        [4, 6, 7],
        [7, 2, 4]])
tensor([[1, 2, 3, 2],
        [1, 4, 6, 7],
        [1, 7, 2, 4]])


In [29]:
import torch
import numpy as np

torch.manual_seed(42)
print("Libraries imported successfully!")

Libraries imported successfully!


In [30]:
X = torch.randn(200, 7)
b = torch.randn(8, 1)
e = torch.randn(200, 1)

print(f"X shape: {X.shape}")
print(f"b shape: {b.shape}")
print(f"e shape: {e.shape}")

print(f"\nFirst 5 rows of X:\n{X[:5]}")
print(f"\nCoefficients b:\n{b.flatten()}")
print(f"\nFirst 5 errors e:\n{e[:5].flatten()}")

X shape: torch.Size([200, 7])
b shape: torch.Size([8, 1])
e shape: torch.Size([200, 1])

First 5 rows of X:
tensor([[ 1.9269,  1.4873,  0.9007, -2.1055,  0.6784, -1.2345, -0.0431],
        [-1.6047, -0.7521,  1.6487, -0.3925, -1.4036, -0.7279, -0.5594],
        [-0.7688,  0.7624,  1.6423, -0.1596, -0.4974,  0.4396, -0.7581],
        [ 1.0783,  0.8008,  1.6806,  1.2791,  1.2964,  0.6105,  1.3347],
        [-0.2316,  0.0418, -0.2516,  0.8599, -1.3847, -0.8712, -0.2234]])

Coefficients b:
tensor([-1.5897, -0.0405,  1.9010, -0.6620,  0.2589, -1.0627, -1.4913,  0.1673])

First 5 errors e:
tensor([ 0.3098, -2.6218, -0.2457,  1.1452,  1.8328])


In [31]:
ones_column = torch.ones(200, 1)

print(f"Ones column shape: {ones_column.shape}")
print(f"First 5 values:\n{ones_column[:5].flatten()}")

Ones column shape: torch.Size([200, 1])
First 5 values:
tensor([1., 1., 1., 1., 1.])


In [33]:
X = torch.cat([ones_column, X], dim=1)

print(f"Modified X shape: {X.shape}")
print(f"First 5 rows of modified X:\n{X[:5]}")
print(f"\nNote: First column is now all 1's (intercept term)")

Modified X shape: torch.Size([200, 8])
First 5 rows of modified X:
tensor([[ 1.0000,  1.9269,  1.4873,  0.9007, -2.1055,  0.6784, -1.2345, -0.0431],
        [ 1.0000, -1.6047, -0.7521,  1.6487, -0.3925, -1.4036, -0.7279, -0.5594],
        [ 1.0000, -0.7688,  0.7624,  1.6423, -0.1596, -0.4974,  0.4396, -0.7581],
        [ 1.0000,  1.0783,  0.8008,  1.6806,  1.2791,  1.2964,  0.6105,  1.3347],
        [ 1.0000, -0.2316,  0.0418, -0.2516,  0.8599, -1.3847, -0.8712, -0.2234]])

Note: First column is now all 1's (intercept term)


In [34]:
y = X @ b + e

print(f"y shape: {y.shape}")
print(f"First 10 values of y:\n{y[:10].flatten()}")

print(f"\nStatistics of y:")
print(f"  Mean: {y.mean().item():.4f}")
print(f"  Std:  {y.std().item():.4f}")
print(f"  Min:  {y.min().item():.4f}")
print(f"  Max:  {y.max().item():.4f}")

y shape: torch.Size([200, 1])
First 10 values of y:
tensor([ 1.4408, -4.2858, -1.7372, -1.8122,  3.4545,  3.5189,  0.5161, -2.2650,
        -2.6999,  0.3262])

Statistics of y:
  Mean: -1.7186
  Std:  2.9011
  Min:  -8.8317
  Max:  6.2392


In [35]:
XtX = X.T @ X
print(f"X^T X shape: {XtX.shape}")

XtX_inv = torch.inverse(XtX)
print(f"(X^T X)^(-1) shape: {XtX_inv.shape}")

Xty = X.T @ y
print(f"X^T y shape: {Xty.shape}")

b_hat = XtX_inv @ Xty
print(f"\nb_hat shape: {b_hat.shape}")

X^T X shape: torch.Size([8, 8])
(X^T X)^(-1) shape: torch.Size([8, 8])
X^T y shape: torch.Size([8, 1])

b_hat shape: torch.Size([8, 1])


In [36]:
print("Comparison of true coefficients (b) vs estimated coefficients (b_hat):")
print("-" * 70)
print(f"{'Index':<10} {'True (b)':<15} {'Estimated (b_hat)':<20} {'Difference':<15}")
print("-" * 70)
for i in range(len(b)):
    diff = abs(b[i].item() - b_hat[i].item())
    print(f"{i:<10} {b[i].item():<15.6f} {b_hat[i].item():<20.6f} {diff:<15.6f}")

print("\nNote: The estimates should be very close to the true values!")

Comparison of true coefficients (b) vs estimated coefficients (b_hat):
----------------------------------------------------------------------
Index      True (b)        Estimated (b_hat)    Difference     
----------------------------------------------------------------------
0          -1.589671       -1.724952            0.135281       
1          -0.040550       -0.015550            0.025000       
2          1.900976        1.990277             0.089301       
3          -0.662040       -0.691611            0.029571       
4          0.258921        0.358052             0.099131       
5          -1.062699       -1.111145            0.048447       
6          -1.491336       -1.525155            0.033820       
7          0.167281        0.317399             0.150118       

Note: The estimates should be very close to the true values!


In [37]:
y_hat = X @ b_hat

print(f"y_hat shape: {y_hat.shape}")
print(f"\nFirst 10 predictions:")
print(f"{'Index':<10} {'True y':<15} {'Predicted y_hat':<20}")
print("-" * 50)
for i in range(10):
    print(f"{i:<10} {y[i].item():<15.6f} {y_hat[i].item():<20.6f}")

y_hat shape: torch.Size([200, 1])

First 10 predictions:
Index      True y          Predicted y_hat     
--------------------------------------------------
0          1.440815        0.943742            
1          -4.285822       -1.985579           
2          -1.737192       -1.746899           
3          -1.812223       -2.800174           
4          3.454528        1.640076            
5          3.518858        2.838308            
6          0.516104        0.559550            
7          -2.265041       -2.413710           
8          -2.699882       -4.426254           
9          0.326241        0.158996            


In [38]:
y_numpy = y.numpy()
y_hat_numpy = y_hat.numpy()

print(f"y_numpy type: {type(y_numpy)}")
print(f"y_numpy shape: {y_numpy.shape}")
print(f"y_hat_numpy type: {type(y_hat_numpy)}")
print(f"y_hat_numpy shape: {y_hat_numpy.shape}")

mse_numpy = np.mean((y_numpy - y_hat_numpy) ** 2)
print(f"\nMean Squared Error (MSE) using NumPy: {mse_numpy:.6f}")

mse_torch = torch.mean((y - y_hat) ** 2)
print(f"Mean Squared Error (MSE) using PyTorch: {mse_torch.item():.6f}")

y_numpy type: <class 'numpy.ndarray'>
y_numpy shape: (200, 1)
y_hat_numpy type: <class 'numpy.ndarray'>
y_hat_numpy shape: (200, 1)

Mean Squared Error (MSE) using NumPy: 0.894395
Mean Squared Error (MSE) using PyTorch: 0.894395


In [39]:
mae = np.mean(np.abs(y_numpy - y_hat_numpy))
rmse = np.sqrt(mse_numpy)

print(f"Additional Metrics:")
print(f"  Mean Absolute Error (MAE): {mae:.6f}")
print(f"  Root Mean Squared Error (RMSE): {rmse:.6f}")

ss_total = np.sum((y_numpy - np.mean(y_numpy)) ** 2)
ss_residual = np.sum((y_numpy - y_hat_numpy) ** 2)
r_squared = 1 - (ss_residual / ss_total)
print(f"  R-squared: {r_squared:.6f}")

Additional Metrics:
  Mean Absolute Error (MAE): 0.763181
  Root Mean Squared Error (RMSE): 0.945724
  R-squared: 0.893199


In [40]:
print("Summary of Results")

print(f"\nData Dimensions:")
print(f"  Number of observations: 200")
print(f"  Number of features: 7 (+ intercept)")
print(f"  Number of coefficients: 8")

print(f"\nModel Performance:")
print(f"  MSE:  {mse_numpy:.6f}")
print(f"  RMSE: {rmse:.6f}")
print(f"  MAE:  {mae:.6f}")
print(f"  R²:   {r_squared:.6f}")

print(f"\nCoefficient Recovery:")
avg_diff = np.mean(np.abs((b - b_hat).numpy()))
print(f"  Average absolute difference: {avg_diff:.6f}")
print(f"  (Should be very small, close to 0)")

Summary of Results

Data Dimensions:
  Number of observations: 200
  Number of features: 7 (+ intercept)
  Number of coefficients: 8

Model Performance:
  MSE:  0.894395
  RMSE: 0.945724
  MAE:  0.763181
  R²:   0.893199

Coefficient Recovery:
  Average absolute difference: 0.076334
  (Should be very small, close to 0)
